---
title: Adapting vulnerability and risk to the assessment of cumulative effects on wildilfe 
author:
  - name: Andrew D. Crosby
    orcid: 0000-0002-9740-8453
    corresponding: true
    email: acrosbynorth@gmail.com
    roles:
      - Conceptualization
      - Analysis
      - Writing
      - Project administration
      - App creation
    affiliation:
      - id: uofa
        name: University of Alberta
        department: Biological Sciences
        group: Alberta Biodiversity Conservation (ABC) Program
        city: Edmonton
        state: Alberta
        country: Canada
      
  - name: Erin M. Bayne
    orcid: 0000-0002-0679-4521
    corresponding: false
    roles: []
    affiliations:
      - ref: uofa
  - name: Scott E. Nielsen
    orcid: 0000-0002-9754-0630
    corresponding: false
    roles: []
    affiliations:
      - ref: uofa
keywords:
  - Wildlife conservation
  - Risk assessment
  - Ecological forecasting
abstract: |
  Cumulative effects of human development on wildlife species can be complex, and are often difficult to assess and predict because of 
plain-language-summary: |
  
key-points:
  - 
date: last-modified
bibliography: references.bib
number-sections: true
---

## Introduction
Many modern conservation problems result from the interacting effects of multiple types of human and natural disturbances on landscape patterns and ecosystem function in what might otherwise be considered largely intact landscapes. For example, large parts of the Canadian boreal region with relatively low human populations and few roads are subject to forest harvest, mineral extraction, and energy development at large scales. The disturbances associated with these combined activities can create cumulative stresses on wildlife populations that go beyond the additive effects of the individual disturbances [@mahon2019]. Understanding the risks to wildlife populations from these cumulative effects, as well as disentangling the effects of individual disturbance types within the context of the whole, is a complex task that is nonetheless necessary for ecosystem-based management and biodiversity conservation. 

Much of the research investigating the effects of development on wildlife involves localized studies of species responses to specific disturbance types (*Dave Roberts summary of oil sands research*). 

* While quantifying species' responses to disturbances (i.e., sensitivity) with empirical research is an important part of understanding effects on wildlife, for conservation purposes the critical state variable to measure is the impact on populations through time. Unfortunately studies examining localized effects on occupancy or density, even if carried out over a large spatial extent, are often difficult to translate into population-level impacts. 

* Population-level consequences of development also depend on the level of exposure to those disturbances. 

* For conservation purposes, quantifying potential population-level consequences from cumulative effects, as well as disentangling the effects of individual industrial sectors within the context of all other disturbances, is the priority (Crosby et al. *in review*). Risks to the population, then, are a function of population-level exposure to disturbances as well as the species response. 



* While some species may be very sensitive to certain types anthropogenic disturbances, if their distribution does not tend to overlap the disturbed areas the population-level consequences are likely to be low. Conversely, even species with low sensitivity might be at risk if they tend to inhabit areas subject to large amounts of disturbance. 

## Methods

### Hierarchical exposure analysis 

We measured population-level exposure to oil sands disturbance in four different ways. The first was simply the proportion of the BCR 6S population within the OSR according to the BAM maps. Second, at the OSR level, we measured the proportion of the OSR population (according to the ABMI predictive maps) within active scheme approvals. Third, we measured the proportion of the OSR population within each scheme approval individually. Fourth, because exploration activities occur outside of scheme approvals throughout the OSR, we measured the overlap of the species distribution with OSR footprint within each prediction grid cell. 

In the first three methods, we calculated an index of exposure as the proportion of the species population within the area of interest divided by the proportion of the population area covered by the area of interest. For example, when measuring exposure of the BCR 6S population, we divided the proportion of the BCR 6S population found within the OSR by the proportion of the area of BCR 6S covered by the OSR. In other words, the denominator represents the expected proportion of the population that would be in the OSR if it were distributed evenly throughout the BCR. An index value >1 indicates greater exposure than would be expected by chance. For the fourth method (grid-level exposure), we calculated the percentage of each grid cell covered by any type of oil sands disturbance (seismic lines, soft linear, hard linear, mines). We then multiplied that percentage by the percentage of the species' reference population within that grid cell as cell-level exposure. Total exposure was the sum of cell-level exposure values across the OSR. 


### Oil sands sensitivity factors 

1. Habitat Loss: Habitat loss refers to the case where disturbances created for oil sands activities change the environment enough, over a large enough area, to be considered loss of habitat. For example, well sites cover ~1 ha, and create a large open area that can nonetheless still be habitat for some species (e.g., Alder Flycatcher). We do not include industrial facilities or compressor stations in our consideration of habitat loss because these sites essentially eliminate all vegetation and, for all intents and purposes, do not constitute any kind of habitat. 

2. d



## Results
* 70 bird species evaluated by ABMI (66%) had negative responses to energy sector disturbances, while 42 (40%) had a coefficient < -50. 


## Discussion 





::: {#refs}
:::
